name: X86_64 Docker Image

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * 0,1,3,5

env:
  PREFIX_URL: https://openwrt.cc/releases/targets
  TARGET: x86
  SUBTARGET: 64
  DEVICE: x86-64-generic
  PLATFORM: x86_64
  ARCH: linux/amd64
  IMAGE_TAG: x86_64

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login To DockerHub
      uses: docker/login-action@v2
      with:
        username: hululuxi
        password: dckr_pat_Prgm6LQ84NPpZct1h58MMx_GEmQ

    - name: Download RootFS Archive
      run: |
        wget -q $PREFIX_URL/$TARGET/$SUBTARGET/immortalwrt-$DEVICE-rootfs.tar.gz
        wget -q https://raw.githubusercontent.com/immortalwrt/immortalwrt/openwrt-21.02/package/emortal/autocore/files/x86/index.htm -O ./data/etc/index.htm

    - name: Build & Push Multiarch Image
      uses: docker/build-push-action@v3
      with:
        platforms: ${{ env.ARCH }}
        file: Dockerfile
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/immortalwrt-mini:${{ env.IMAGE_TAG }}
